require 'dm-core'
require 'lib/type'
require 'lib/naming_convention'

adapter = DataMapper.setup(:default,{
  :adapter => 'postgres',
  :username => 'focus',
  :database => 'focus_development',
  :host => 'localhost'
})
adapter.resource_naming_convention = NamingConventions::Resource::UnderscoredAndPluralizedWithPrefix

DataObjects::Postgres.logger = DataObjects::Logger.new(STDOUT, 0)

require 'versions/8_3/administrable_role_authorization'
require 'versions/8_3/applicable_role'
require 'versions/8_3/attribute'
require 'versions/8_3/check_constraint'
require 'versions/8_3/check_constraint_routine_usage'
require 'versions/8_3/column'
require 'versions/8_3/column_domain_usage'
require 'versions/8_3/column_privilege'
require 'versions/8_3/column_udt_usage'
require 'versions/8_3/constraint_column_usage'
require 'versions/8_3/constraint_table_usage'
require 'versions/8_3/data_type_privilege'
require 'versions/8_3/domain'
require 'versions/8_3/domain_constraint'
require 'versions/8_3/domain_udt_usage'
require 'versions/8_3/element_type'
require 'versions/8_3/enabled_role'
require 'versions/8_3/information_schema_catalog_name'
require 'versions/8_3/key_column_usage'
require 'versions/8_3/parameter'
require 'versions/8_3/referential_constraint'
require 'versions/8_3/role_column_grant'
require 'versions/8_3/role_routine_grant'
require 'versions/8_3/role_table_grant'
require 'versions/8_3/role_usage_grant'
require 'versions/8_3/routine'
require 'versions/8_3/routine_privilege'
require 'versions/8_3/schemata'
require 'versions/8_3/sequence'
require 'versions/8_3/sql_feature'
require 'versions/8_3/sql_implementation_info'
require 'versions/8_3/sql_language'
require 'versions/8_3/sql_package'
require 'versions/8_3/sql_part'
require 'versions/8_3/sql_sizing'
require 'versions/8_3/sql_sizing_profile'
require 'versions/8_3/table'
require 'versions/8_3/table_constraint'
require 'versions/8_3/table_privilege'
require 'versions/8_3/trigger'
require 'versions/8_3/usage_privilege'
require 'versions/8_3/view'
require 'versions/8_3/view_column_usage'
require 'versions/8_3/view_routine_usage'
require 'versions/8_3/view_table_usage'

# require 'versions/8_3/check_constraint'
